gems: [jekyll-paginate]

# Site settings
title: JmxInWeb
SEOTitle: JmxInWeb
header-img: img/home-bg-o.jpg
email: liangwj72@qq.com
description: "Jmx Web UI Management"
keyword: "Java, 开源, JMX, WEB, bootstrap"
url: "http://ynitq.github.io/"              # your host, for absolute URL
baseurl: "/JmxInWeb"                        # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
#weibo_username:     huxpro
#zhihu_username:     huxpro
github_username:    ynitq
#twitter_username:  huxpro
#facebook_username:  huxpro



# Build settings
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: ynitq
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing

# Baidu Analytics
# ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "写写代码，做做设计，看看产品。世界那么大，我想去看看。"

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# Friends
friends: [
    {
        title: "云南IT圈",
        href: "http://www.ynitq.com/"
    },{
        title: "Hux Theme",
        href: "https://github.com/Huxpro/huxpro.github.io"
    }
]
